name: tutorial-env
channels:
  - rapidsai
  - rapidsai-nightly
  - conda-forge
  - nvidia
dependencies:
  - python>=3.11
  - numpy
  - pandas
  - snakeviz
  - xarray
  - netcdf4
  - cupy>=14
  - cudf=26.8.0a894
  - cuml=26.8.0a145
  - cuda-python
  - cupy-xarray
  - cuda-core
  - ipykernel
  - rapids-cli>=0.2.0
