[workspace]
name = "tutorial-env"
channels = ["rapidsai-nightly", "rapidsai", "conda-forge", "nvidia"]
platforms = ["linux-64"]

[dependencies]
python = ">=3.11"
numpy = "*"
pandas = "*"
snakeviz = "*"
xarray = "*"
netcdf4 = "*"
cupy = ">=14"
cuda-python = "*"
cupy-xarray = "*"
cuda-core = "*"
cudf = "26.8.0a894"
cuml = "26.8.0a145"
ipykernel = "*"
rapids-cli = ">=0.2.0"
ipython = "*"
jupyter = "*"
marimo = "*"
scikit-learn = "*"
napari = "*"


